---
title: "Massbuilds_compile"
format: html
editor: visual
---

# 1 - Setup: paths and parameters

```{r, setup, include=FALSE}

pacman::p_load(
  sf,
  data.table,
  tidycensus,
  tidyverse,
  openxlsx,
  tidygeocoder,
  lehdr,
  reticulate
)

reticulate::use_python("C:/Program Files/ArcGIS/Pro/bin/Python/envs/arcgispro-py3/python.exe")

# devtools::install_github('MAPC/mapcdatakeys')
library(mapcdatakeys)

# Paths
if (grepl('VM',Sys.info()[['nodename']])){
  base <- '//data-sync/Public/DataServices'
} else {
  base <- 'S:/Network Shares/K Drive/DataServices'
}


data_path <- file.path(base,'Projects/Current_Projects/Environment/EEA_MLCA/Data')

project_gdb <- file.path(data_path, 'Spatial/EEA_MLCA.gdb')

proj_gpkg <- file.path(data_path, 'Spatial/EEA_MLCA.gpkg')

urbsim_gpkg <- file.path(data_path, 'Spatial/urbansim_geographies.gpkg')

parcel_mb_gpkg <- file.path(data_path, 'Spatial/parcels_with_massbuilds_projects.gpkg')

massbuilds_gpkg <- file.path(data_path, 'Spatial/all_massbuilds.gpkg')

task3_gdb = paste0(data_path, '/Task_3/Spatial/LandUse_Efficiency_Metrics.gdb')

scen = 'Scen_0'

years=c(2010, 2019, 2024, 2029, 2034)
# years=c(2019, 2024, 2029, 2034, 2039, 2044, 2049)

# Municipalities
munis <- all_muni_data_keys |> 
  select(muni_id, rpa_acr, mpo) |> 
  setDT()

# Existing setup (non-scenario)
# MAPCM_run <- 'run_228'
# SWM_run <- 'state_run_135'

# Scenario 1 (Where We Were)
scen <- 'Scenario_1'
MAPCM_run <- 's100'
SWM_run <- 's62'

# Scenario 2 (Current Policies)
# scen <- 'Scenario_2'
# MAPCM_run <- 's101'
# SWM_run <- 's63'

# Scenario 3 ()
# scen <- 'Scenario_3'
# MAPCM_run <- ''
# SWM_run <- ''

# Scenario 4 ()
# scen <- 'Scenario_4'
# MAPCM_run <- ''
# SWM_run <- ''


# Conservation Test

# years <- c(2011,2012,2013,2014)
# scen='Conservation_test'
# MAPCM_run <- 'run_234'
# scen_gdb <- paste0(base, '/Projects/Current_Projects/Environment/EEA_MLCA/Data/UrbanSim/',scen,'/',scen,'.gdb')

# 2010 Blocks
blk_2010 <- geog_xw_2010 |> 
  left_join(munis, by = 'muni_id') |> 
  select(bl10_id, muni_id, muni_name, rpa_acr, mpo) |> 
  setDT()

mapc_blks <- blk_2010 |> filter(rpa_acr=='MAPC') |> pull(bl10_id)
  
blk10_sf <- mapcdatakeys::block_sf(2010) |> 
  left_join(munis, by='muni_id')

knitr::opts_knit$set(root.dir = data_path)
```

# 2 - Massbuilds compile

```{r}

mapc.mb <- fread(paste0(data_path,'/Massbuilds/MAPC_all_devprojects_4_7_2026.csv')) |> 
  select(block_id,project_id,identification,name,address,start_year,building_type,residential_units,own_units,rent_units,avg_unit_sqft,employment_capacity,status,redevelopment,tags) |> 
  mutate(model='mapc',
         identification = case_when(identification==6512 ~ 6609,.default=identification),
         ID=identification)
swm.mb <- fread(paste0(data_path,'/Massbuilds/SWM_all_devprojects_4_7_2026.csv')) |> 
  select(block_id,project_id,identification,name,address,start_year,building_type,residential_units,own_units,rent_units,avg_unit_sqft,employment_capacity,status,redevelopment,tags) |> 
  filter(!identification %in% mapc.mb$identification & !block_id %in% as.character(mapc_blks)) |> 
  mutate(model='swm',
         ID = identification)

mb <- rbind(mapc.mb,swm.mb) |> 
  mutate(source='urbansim') |> 
  setDT()

not_incl <- c(
  6664,
  7056,
  7060,
  7104,
  7105,
  7155,
  6690,
  7016,
  7052,
  7091,
  7213,
  7054,
  7055,
  7065,
  7066,
  7094,
  7096,
  6704,
  7015,
  7058,
  7061,
  7063,
  7067,
  7082,
  7084,
  7093,
  6740,
  6741,
  6742,
  6743,
  6745,
  6992,
  6995,
  7000,
  7001,
  7002,
  7003,
  7004,
  7005,
  7006,
  7007,
  7008,
  7009,
  7010,
  7011,
  7031,
  7032,
  7033,
  7034,
  7036,
  7037,
  7038,
  7039,
  7040,
  7041,
  7042,
  7044,
  7045,
  7048,
  7050,
  7053,
  7057,
  7070,
  7072,
  7078,
  7079,
  7080,
  7081,
  7086,
  7092,
  7095,
  7097,
  7098,
  7099,
  7101,
  7108,
  7109
)

mb.shp <- st_read(paste0(data_path,'/Massbuilds/massbuilds-shp-20260407.shp')) %>%
  st_transform(.,crs=4326) %>%
  mutate(lon = st_coordinates(.)[,1],
         lat = st_coordinates(.)[,2]) |> 
  mutate(source='website') |> 
  select(ID,lon,lat,source) |> 
  filter(!ID %in% not_incl) |> 
  right_join(mb, by='ID') |> 
  setDT()


# Geocode entries from NMCOG Scenario Update

nmcog <- mb.shp[grepl('nmcog_addon',tags)] |> pull(name) |> unique()
nm.xy <- geo_combine(
      queries = list(
        list(method = 'arcgis'),
        list(method = 'osm')),
      address = nmcog,
      global_params = list(address = 'address'),
      lat = lat,
      lon = lon
    )

fix <- mb.shp[grepl('nmcog_addon',tags)] |> 
  select(-lon,-lat) |> 
  left_join(nm.xy,by=c('name'='address')) |> 
  select(-query) |> 
  mutate(identification=99999,
         ID=99999)

mb.shp <- mb.shp[!grepl('nmcog_addon',tags)] |> 
  rbind(fix)

# Projects that have been deleted from www.massbuilds.com but not from UrbanSim

to.delete <- mb.shp[is.na(lon) & !is.na(identification), .(project_id,name,identification,model)]
fwrite(to.delete, paste0(data_path,'/Massbuilds/to_delete_from_urbansim.csv'))


# NMCOG projects need to be added to Massbuilds and then their massbuilds IDs transferred into Urbansim

swm_ids <- fread("S:/Network Shares/K Drive/DataServices/Projects/Current_Projects/Projections/Projections_2028/Data/02_UrbanSim/Massbuilds/Massbuilds_to_add_to_Urbancanvas_20260325_clean.csv")

to.add <- mb.shp[is.na(identification) | tags=='nmcog_addon_20260320', .(project_id,name,model,tags,ID)] |> 
  left_join(swm_ids |> select(identification,full_address), by=c('name'='full_address'), relationship='many-to-many') |> 
  setDT()

fwrite(to.add, paste0(data_path,'/Massbuilds/to_add_ID_on_urbansim.csv'))


# Geocode recent direct-to-urbansim updates of dev projects

swm.geo <- to.add |> filter(is.na(ID)) |> pull(name) |> unique()
swm.xy <- geo_combine(
      queries = list(
        list(method = 'arcgis'),
        list(method = 'osm')),
      address = swm.geo,
      global_params = list(address = 'address'),
      lat = lat,
      lon = lon
    )

fix2 <- mb.shp[name %in% swm.geo] |> 
  select(-lon,-lat) |> 
  left_join(swm.xy,by=c('name'='address')) |> 
  select(-query)

# Final combination for export

mb.cln <- mb.shp[!name %in% c(swm.geo,to.delete$name)] |>
  rbind(fix2) %>%
  st_drop_geometry() |>
  select(-geometry) %>%
  mutate(
    lat = case_when(name == 'Pine Oaks Village IV' ~ 41.694054, .default = lat),
    lon = case_when(name == 'Pine Oaks Village IV' ~ -70.105703, .default = lon),
    latitude = lat,
    longitude = lon
  ) %>%
  st_as_sf(coords = c('lon', 'lat'), crs = 4326) %>%
  st_transform(crs = st_crs(blk10_sf)) |>
  select(-c(source.x, source.y))

st_write(mb.cln, 
         dsn=project_gdb,
         layer='All_Massbuilds_Projects_in_UrbanSim_20260407',
         append=F)

# Visual inspection identified 4 projects with incorrect lat/lon values
# Edits made in ArcGIS directly (updates to website done afterwards)

mb2 <- st_read(dsn=project_gdb,
         layer='All_Massbuilds_Projects_in_UrbanSim_20260407_manual_point_fixed')


# Join massbuilds points to MBTA 3A zones

chk <- st_read(paste0(data_path,'/Massbuilds/massbuilds-shp-20260407.shp')) |> 
  select(ID,CREATED_AT,UPDATED_AT) |> 
  mutate(create_date=lubridate::ymd_hms(CREATED_AT),
         update_date=lubridate::ymd_hms(UPDATED_AT)
  ) |> 
  select(ID,create_date,update_date) |> 
  st_drop_geometry() |> 
  setDT()

poly3A <- st_read(dsn=project_gdb,
                  layer='Districts_3A_20260122_max_dua') |> 
  st_transform(crs=st_crs(mb2))

# Filter to recent multifamily projects only

mb3a <- st_join(mb2, poly3A, join=st_within, left = F) |>
  filter(
    !is.na(max_dua_3A) &
      start_year >= 2025 &
      building_type %in% c('Own Multifamily', 'Rent Multifamily')
    ) |> 
  left_join(chk, by='ID') |> 
  filter(tags=='nmcog_addon_20260320' | create_date >= '2022-01-01 00:00:00'| update_date >= '2022-01-01 00:00:00') |> 
  setDT()

# Combine with list of State Land for Housing projects to make list of projects to exclude from EEA Scenario 1 - "Where We Were"

slh <- mb2 |> filter(grepl('EEA_Scenario_2',tags)) |> setDT()
scen1_excluded_mb <- rbind(mb3a, slh, fill=T) |> 
  select(-create_date,-update_date) %>%
  st_as_sf(.)

st_write(scen1_excluded_mb, 
         dsn=project_gdb,
         layer='Final_set_of_massbuilds_projects_excluded_from_Scenario_1',
         append=F)

fwrite(mb3a,paste0(data_path,'/Massbuilds/Final_massbuilds_3A_projects_to_exclude_from_Scenario_1.csv'))

fwrite(mb2 |> setDT(), paste0(data_path,'/Massbuilds/All_Massbuilds_Projects_in_UrbanSim_20260407_final_version.csv'))


# Identify parcels containing Massbuilds project for Harvard Forest to exclude from future conservation areas

all.mb <- st_read(dsn=project_gdb, layer='All_Massbuilds_Projects_in_UrbanSim_20260407_manual_point_fixed')

par <- st_read(dsn = scratch, layer = 'main_L3_TAXPAR_POLY_WITH_COMPRESSED_ASSESSORS_TABLE_20260325_noROW') |> filter(LOC_ID!='F_697064_2863485')

par.near <- st_nearest_feature(all.mb, par)
par.mb <- par[par.near,]
par.mb <- par.mb |> 
  mutate(hasMassBuilds=1)

st_write(par.mb, dsn = parcel_mb_gpkg, layer = 'parcels_with_massbuilds_projects', append=F)
st_write(all.mb, dsn = massbuilds_gpkg, layer = 'all_massbuilds_projects_in_urbansim_20260407', append=F)

st_write(par.mb, dsn = project_gdb, layer = 'parcels_with_massbuilds_projects', append=F)
st_write(all.mb, dsn = project_gdb, layer = 'All_Massbuilds_Projects_in_Urbansim_20260407_final_version', append=F)


```
