---
title: "Scenarios 3 and 4 Inputs"
author: "Conor Gately"
format: html
editor: source
---

# 1 - Setup: paths and parameters

```{r, setup, include=FALSE}

pacman::p_load(
  sf,
  data.table,
  tidycensus,
  tidyverse,
  openxlsx,
  tidygeocoder,
  terra,
  reticulate
)

options(scipen = 999)
set.seed(351)

# devtools::install_github('MAPC/mapcdatakeys')
library(mapcdatakeys)


# reticulate::use_python("C:/Program Files/ArcGIS/Pro/bin/Python/envs/arcgispro-py3/python.exe")

# Paths
if (grepl('VM',Sys.info()[['nodename']])){
  base <- '//data-sync/Public/DataServices'
} else {
  base <- 'S:/Network Shares/K Drive/DataServices'
}


data_path <- file.path(base,'Projects/Current_Projects/Environment/EEA_MLCA/Data')

scen3_path = paste0(data_path,'/Task_4/Scenario_3/')
sp3_path <- paste0(scen3_path,'Inputs/Spatial/')
scen3_gdb = paste0(sp3_path, 'Scenario_3.gdb')

scen4_path = paste0(data_path,'/Task_4/Scenario_4/')
sp4_path <- paste0(scen4_path,'Inputs/Spatial/')
scen4_gdb = paste0(sp4_path, 'Scenario_4.gdb')

knitr::opts_knit$set(root.dir = data_path)
```

# 2 - Zoning Constraint Adjustments

```{r}

# Residential parcel land use codes


res.codes <- c(
  '010',
  '012',
  '013',
  '014',
  '016',
  '017',
  '018',
  '019',
  '061',
  '071',
  '081',
  '091',
  10,
  12,
  13,
  14,
  16,
  17,
  18,
  19,
  61,
  71,
  81,
  91,
  945,
  959,
  970,
  973,
  100:131,
  133:139,
  150:199
)

res.par <- st_read(dsn = scen_gdb, layer = "parcel_sewer_service_area_constraint_erase") |>
  filter(MIN_LUCA %in% as.character(res.codes))

st_write(res.par,
         dsn = scen_gdb,
         layer = 'res_parcels_in_sewer_service_area',
         append = F)

res.sewer <- st_union(res.par)

st_write(res.sewer,
         dsn = scen_gdb,
         layer = 'residential_area_with_sewer_service_dissolve',
         append = F)

tod <- st_read(dsn = scen3_gdb, layer = 'Rail_stations_buffer_zoning_inter')
setDT(tod)

tod[, max_far_inter := max(max_far), FID_Rail_stations_buffer]
tod[, max_dua_inter := max(max_dua), FID_Rail_stations_buffer]

tod.tab <- tod[, .(FID_Rail_stations_buffer, max_dua_inter, max_far_inter, Shape)]
tod.tab[max_dua_inter < 100 & max_dua_inter > 0, max_dua_inter := 100]
tod.tab[, zoning := 'TOD_DUA100']
setnames(tod.tab, c('id', 'max_dua', 'max_far', 'zoning', 'Shape'))

tod.sf <- st_to_sf(tod.tab)
st_write(tod.sf, dsn = scen4_gdb, layer = 'TOD_100dua_zones', append=F)

```


# 3 - Development Pipeline Adjustments

```{r}

blk2010 <- mapcdatakeys::block_sf(2010)

mapc.blks <- left_join(blk2010,
                       mapcdatakeys::all_muni_data_keys |> select(muni_id, rpa_acr),
                       by = 'muni_id') |>
  filter(rpa_acr == 'MAPC') |>
  pull(bl10_id) |>
  unique()

sewer <- st_read(dsn = scen4_gdb, layer = 'parcel_sewer_service_area_constraint_erase')

ruc <- mapcdatakeys::all_muni_data_keys |>
  select(muni_id, cmtyp08) |>
  right_join(mapcdatakeys::muni_sf(2020), by = 'muni_id') |>
  filter(cmtyp08 == 'Regional Urban Center')

ruc.blk <- mapcdatakeys::block_sf(2010) |>
  filter(muni_id %in% ruc$muni_id) |>
  st_intersection(sewer)

tod.sf <- st_read(dsn = scen4_gdb, layer = 'TOD_100dua_zones')

tod.blk <- blk2010 |>
  st_intersection(tod.sf)

non.cr.ruc <- ruc |> filter(!muni_id %in% tod.blk$muni_id)
non.cr.ruc.blk <- ruc.blk |> filter(!muni_id %in% tod.blk$muni_id)

res.blks <- blk2010 |>
  filter(bl10_id %in% non.cr.ruc.blk$bl10_id |
           bl10_id %in% tod.blk$bl10_id) |>
  pull(bl10_id) |>
  unique()

mb.raw <- st_read(dsn = file.path(data_path, 'Spatial/all_massbuilds.gpkg'),
                  layer = 'all_massbuilds_projects_in_urbansim_20260407') |>
  setDT()

mb25to50 <- mb.raw |>
  st_drop_geometry() |>
  filter(start_year > 2024) |>
  select(identification,
         start_year,
         residential_units,
         employment_capacity) |>
  mutate(
    res_proj = case_when(residential_units > 0 ~ 1, .default = 0),
    comm_proj = case_when(employment_capacity > 0 ~ 1, .default = 0)
  ) |>
  group_by(start_year) |>
  summarize(
    mb_emp_cap_added = sum(employment_capacity, na.rm = T),
    mb_res_units_added = sum(residential_units, na.rm = T),
    avg_emp_cap = median(employment_capacity, na.rm = T),
    avg_res_units_added = median(residential_units, na.rm = T),
    res_proj = sum(res_proj),
    comm_proj = sum(comm_proj)
  )

res.target <- round(sum(mb25to50$mb_res_units_added) * .15 / 100)
# 176 developments at 100 units each

com.target <- round(sum(mb25to50$mb_emp_cap_added) * .15 / 120)
# 406 developments at 120 'employment capacity' each

samp.years <- seq(2025, 2035)

res.sample.blks <- sample(res.blks, res.target, replace = FALSE)
com.sample.blks <- sample(res.blks, com.target, replace = FALSE)

# Create formatted development pipeline tables for UrbanSim bulk upload

res.sim <- data.table(
  block_id = res.sample.blks,
  project_id = seq(max(mb.raw$project_id) + 1, max(mb.raw$project_id) + res.target),
  name = paste0('residential_simulated_development_', 1:res.target),
  building_type_id = rep(1, res.target),
  start_year = sample(samp.years, res.target, replace = TRUE),
  duration = rep(1, res.target),
  status = rep('Committed', res.target),
  redevelopment = rep(0, res.target),
  tags = rep('EEA_simulated_developments', res.target),
  phased = rep('FALSE', res.target),
  buildings_count = rep(1, res.target),
  floors = rep(3, res.target),
  descriptive_location = rep('', res.target),
  street = rep('', res.target),
  city = rep('', res.target),
  state = rep('MA', res.target),
  zip = rep('', res.target),
  identification = NA,
  developer = NA,
  source = 'mapc',
  notes = rep('', res.target),
  residential_units = rep(100, res.target),
  average_unit_size = rep(1000, res.target),
  market_rate_units = rep(100, res.target),
  affordable_units = rep(0, res.target),
  own_units = rep(100, res.target),
  rent_units = rep(0, res.target)
)

com.sim <- data.table(
  block_id = com.sample.blks,
  project_id = seq(
    max(res.sim$project_id) + 1,
    max(res.sim$project_id) + com.target
  ),
  name = paste0('nonresidential_simulated_development_', 1:com.target),
  building_type_id = rep(5, com.target),
  start_year = sample(samp.years, com.target, replace = TRUE),
  duration = rep(1, com.target),
  status = rep('Committed', com.target),
  redevelopment = rep(0, com.target),
  tags = rep('EEA_simulated_developments', com.target),
  phased = rep('FALSE', com.target),
  buildings_count = rep(1, com.target),
  floors = rep(2, com.target),
  descriptive_location = rep('', com.target),
  street = rep('', com.target),
  city = rep('', com.target),
  state = rep('MA', com.target),
  zip = rep('', com.target),
  identification = NA,
  developer = NA,
  source = 'mapc',
  notes = rep('', com.target),
  employment_capacity = rep(120, com.target)
)

mapc.res <- res.sim |> filter(block_id %in% mapc.blks)
mapc.com <- com.sim |> filter(block_id %in% mapc.blks)

fwrite(
  res.sim,
  paste0(
    scen3_path,
    'Inputs/swm_residential_development_simulated_EEA_Scenario_3_and_4.csv'
  )
)
fwrite(
  com.sim,
  paste0(
    scen3_path,
    'Inputs/swm_nonresidential_development_simulated_EEA_Scenario_3_and_4.csv'
  )
)
fwrite(
  mapc.res,
  paste0(
    scen3_path,
    'Inputs/mapcm_residential_development_simulated_EEA_Scenario_3_and_4.csv'
  )
)
fwrite(
  mapc.com,
  paste0(
    scen3_path,
    'Inputs/mapcm_nonresidential_development_simulated_EEA_Scenario_3_and_4.csv'
  )
)


```

# 4 - Temp Zoning Adjustments Scen 4

```{r}

e4 <- st_read(dsn = scen4_gdb, layer = 'EEA_Scenario_4_conservation_TOD_erase')
tod <- st_read(dsn = scen4_gdb, layer = 'TOD_100dua_zones')
cons <- st_read(dsn = scen4_gdb, layer = 'Scenario_3_and_4_conservation2050')

s4.comp <- rbind(e4, tod, cons)
st_write(s4.comp,dsn=scen4_gdb,layer='EEA_Scenario_4_merged_with_gaps')

```

# 5 - Convert Zoning Spatial Layer into Block-level constraints for UrbanCanvas

```{r}

gp <- st_read(dsn = file.path(scen3_sp_path,'mapc_uc_constraints_update_20241011.gpkg'), layer = 'mapc_uc_constraints_revised_20241011')

s3 <- fread(paste0(base_sp,'/EEA_scratch/EEA_Scenario_3_zoning_block_inter.csv'))

b3 <- s3 |> 
  mutate(block_id_2010 = as.character(bl10_id)) |> 
  group_by(block_id_2010) |> 
  summarize(
    total_units = sum(total_units),
    total_jobs = sum(total_jobs),
    area_m2 = sum(Shape_Area)
  ) |> 
  ungroup() |> 
  mutate(
    area_acres = area_m2 * 0.000247105,
    max_dua = total_units / area_acres,
    max_eda = total_jobs / area_acres,
    start_date = 2023,
    end_date = 2050,
    name = "EEA_Scenario_3_constraints",
    notes = "EEA_Scenario_3_constraints",
    tags = "EEA_Scenario_3_constraints"
    ) |> 
  select(block_id_2010, max_dua,max_eda, start_date, end_date, name, notes, tags) |> 
  setDT()
b3[,uc_constraint_id:=.I]
fwrite(b3,paste0(base_sp,'/EEA_Scenario_3_zoning_constraints_block2010.csv'))


s4 <- fread(paste0(base_sp,'/EEA_scratch/EEA_Scenario_4_zoning_block_inter.csv'))

b4 <- s4 |> 
  mutate(block_id_2010 = as.character(bl10_id)) |> 
  group_by(block_id_2010) |> 
  summarize(
    total_units = sum(total_units),
    total_jobs = sum(total_jobs),
    area_m2 = sum(Shape_Area)
  ) |> 
  ungroup() |> 
  mutate(
    area_acres = area_m2 * 0.000247105,
    max_dua = total_units / area_acres,
    max_eda = total_jobs / area_acres,
    start_date = 2023,
    end_date = 2050,
    name = "EEA_Scenario_4_constraints",
    notes = "EEA_Scenario_4_constraints",
    tags = "EEA_Scenario_4_constraints"
    ) |> 
  select(block_id_2010, max_dua,max_eda, start_date, end_date, name, notes, tags) |> 
  setDT()
b4[,uc_constraint_id:=.I]
fwrite(b4,paste0(base_sp,'/EEA_Scenario_4_zoning_constraints_block2010.csv'))

mapc.blks <- fread(paste0(base_sp,'/EEA_scratch/mapc_census_blocks_2010.csv')) |> 
  mutate(block_id = as.character(block_id))

m3 <- b3 |> filter(block_id_2010 %in% mapc.blks$block_id)
m4 <- b4 |> filter(block_id_2010 %in% mapc.blks$block_id)


fwrite(m3,paste0(base_sp,'/EEA_Scenario_3_MAPCM_zoning_constraints_block2010.csv'))

fwrite(m4,paste0(base_sp,'/EEA_Scenario_4_MAPCM_zoning_constraints_block2010.csv'))

```
